Repository twosixlabs/armory, pull requests merged in 2020-10, with the labels that each got.

#790 training set to True
  armory/scenarios/image_classification.py
Labels: bug

#792 Configurable magic number for Apricot dataset
  armory/data/adversarial_datasets.py
Labels: datasets

#806 Update xView test to use mAP
  tests/test_pytorch/test_pytorch_models.py
Labels: test cases

#829 Canonical preprocessing for adversarial datasets and non-scenario datasets
  armory/data/adversarial_datasets.py
  armory/data/datasets.py
Labels: datasets

#840 update download command line
  armory/__main__.py
  docs/getting_started.md
Labels: user facing

#845 Update attack params
  scenario_configs/asr_deepspeech_baseline.json
Labels: bug

#832 fast untarring when possible
  armory/data/utils.py
Labels: performance

#842 Piping from stdin
  armory/__main__.py
  armory/utils/configuration.py
  docs/command_line.md
Labels: user facing
